[build]
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput --settings=fintrack.settings_prod"

[deploy]
startCommand = "gunicorn fintrack.wsgi:application --workers 4 --bind 0.0.0.0:$PORT"
