# Generated by Django 6.0.2 on 2026-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('bank', 'Bank')], default='manual', max_length=10),
        ),
    ]
