# Generated by Django 6.0.2 on 2026-04-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_add_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('bank', 'Bank'), ('subscription', 'Subscription')], default='manual', max_length=12),
        ),
    ]
