# Generated by Django 6.0.2 on 2026-03-19 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_categorybudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categorybudget',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorybudget',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together={('user', 'category', 'month', 'year')},
        ),
    ]
