# Generated by Django 6.0.2 on 2026-03-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userprofile_onboarding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingscontribution',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='customcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savingscontribution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_income',
        ),
    ]
