# Generated by Django 6.0.2 on 2026-04-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='saved',
        ),
    ]
