# Generated by Django 6.0.2 on 2026-07-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_add_model_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly — ₹49'), ('yearly', 'Yearly — ₹499')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='categorybudget',
            new_name='dashboard_c_user_id_ab7313_idx',
            old_name='dashboard_c_user_id_month_year_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='dashboard_i_user_id_c70c66_idx',
            old_name='dashboard_i_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='dashboard_i_user_id_a6ecda_idx',
            old_name='dashboard_i_user_id_source_idx',
        ),
        migrations.RenameIndex(
            model_name='savingscontribution',
            new_name='dashboard_s_goal_id_a31fcf_idx',
            old_name='dashboard_s_goal_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='savingsgoal',
            new_name='dashboard_s_user_id_9afda3_idx',
            old_name='dashboard_s_user_id_target_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='dashboard_s_user_id_baefde_idx',
            old_name='dashboard_s_user_status_next_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly Pro'), ('yearly', 'Yearly Pro')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_p_user_id_66287c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='dashboard_p_razorpa_740477_idx'),
        ),
    ]
